### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [ruby-processing/JRubyArt-examples#5]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by monkstone** [comment]
Currently I am using a blue ruby image as my favicon and a svg file on the website. https://ruby-processing.github.io/JRubyArt. You are welcome to design an alternative, no guarantees it will get used, but if is clearly better I don't mind attributing design credits.

**Comment by monkstone** [comment]
Empty promise.
